### ISSUE TITLE
File Not Found during the download of mod from Admirall Bulldog App

### ISSUE THREAD

**Issue by UkrainianCitizen** [MrBean355/admiralbulldog-mod#21]
Here the log
[crash_log.txt](https://github.com/MrBean355/admiralbulldog-mod/files/4496504/crash_log.txt)

**Comment by MrBean355** [comment]
Hi @UkrainianCitizen 
Please close Dota 2 before updating the mod.
I'll put a message in the app that mentions this.
Sorry!
