### ISSUE TITLE
Changing icons

### ISSUE THREAD

**Issue by rubyzera** [MrBean355/admiralbulldog-mod#22]
Hi, i want to know if it's possible to choose the modified icons individually. Personally i think it's funnier to use the sadKEK image on the BKB rather than the one on the mod. Can you add the feature on the mod to change that, or teach how to open the vpk and make that change?

![4](https://user-images.githubusercontent.com/65840302/83557796-a5d83780-a4e8-11ea-8bcd-50c6f58cb314.png)

Thanks in advance

**Comment by MrBean355** [comment]
Hey @rubyzera, sorry for not replying on your other issue.

I've spent some time trying to figure out how to implement such functionality.
Sadly it's quite a complicated procedure to build the mod.
Making it customisable means that it would have to be built on each user's computer, which is looking infeasible at this point.
Unfortunately I'll be keeping the mod as a "package deal" for now, until I can find out a way to make it work.

I've made a special mod which just changes the BKB icon: [pak01_dir.zip](https://github.com/MrBean355/admiralbulldog-mod/files/4719751/pak01_dir.zip)
This will work alongside my original mod; only replacing the BKB icon.
Installation:
1. Download & extract the above file.
2. It will give you a `pak01_dir.vpk` file. Copy this now.
3. Navigate to your Dota 2 installation folder.
4. Within there, open the `game` folder.
5. In here, create a new folder: `sadkek`.
6. Paste the `pak01_dir.vpk` file inside this new folder.
7. Go back up to the `game` folder and open `dota`.
8. Find the `gameinfo.gi` file and open it in a text editor.
9. Near the top there will be a `SearchPaths` section:
![Annotation 2020-06-02 232513](https://user-images.githubusercontent.com/6640530/83571584-59ace780-a528-11ea-9795-8dfc97b329e5.png)
10. Edit the file to resemble the red block in the screenshot. Importantly `Game sadkek` is above `Game admiralbulldog` and `Game dota`.
11. Save the file & start up Dota.

Please shout if I can help with this process.

**Comment by rubyzera** [comment]
Thanks for the reply, and don't worry about not replying, i wrote the issue on the wrong place (the sounds mod rather than here). I followed your instructions and it worked perfectly. And it's okay not to implement that feature, source based games always were weird to mod but this one will do. Thanks again and best regards :)

**Comment by MrBean355** [comment]
Thank you, glad it works! Hope you enjoy the project.
